// This file will be auto-generated by Wails during build
// These are temporary type declarations for development

export function CheckVaultExists(): Promise<boolean>;
export function CreateVault(masterPassword: string): Promise<void>;
export function UnlockVault(masterPassword: string): Promise<void>;
export function IsUnlocked(): Promise<boolean>;
export function GetAllCredentials(): Promise<any[]>;
export function AddCredential(
  serviceName: string,
  url: string,
  username: string,
  password: string,
  category: string
): Promise<void>;
export function UpdateCredential(
  id: string,
  serviceName: string,
  url: string,
  username: string,
  password: string,
  category: string
): Promise<void>;
export function DeleteCredential(id: string): Promise<void>;
export function CopyPassword(id: string): Promise<void>;
export function CopyUsername(id: string): Promise<void>;
export function LockVault(): void;

export interface PasswordGeneratorOptions {
  length: number;
  includeUppercase: boolean;
  includeLowercase: boolean;
  includeNumbers: boolean;
  includeSymbols: boolean;
  excludeAmbiguous: boolean;
}

export function GeneratePasswordWithOptions(options: PasswordGeneratorOptions): Promise<string>;
export function GenerateQuickPassword(length: number): Promise<string>;

export interface ImportResult {
  totalProcessed: number;
  imported: number;
  skipped: number;
  errors: string[];
}

export function ImportFromCSV(csvContent: string): Promise<ImportResult>;
export function DeleteVault(): Promise<void>;
